### ISSUE TITLE
Add headers to data files

### ISSUE THREAD

**Issue by thefferon** [ncbi/dbvar#5]
I suggest including a header line at the top of each file - so we don't have to look them up in the README, and copy them into the file if we need them there.

I would also suggest changing some of the header names. In the README they are:

chr
outermost_start
outermost_stop
SV_count
variant_type
method
analysis
platform
study
SV

It's not completely clear what some of these are:

1. Why 'outermost_start' and 'outermost_stop'? Are there other coordinates we are not seeing in the data file? How do we know what they represent?
2. What is 'SV_count'? How does it relate to "nsv"s and "nssvs"?
3. How do we look up a publication mentioned in the "study" column? Do you have citations somewhere?

**Comment by JohnG-001** [comment]
Hi @thefferon , thanks for your interest, and for creating this issue.

> **1. Why 'outermost_start' and 'outermost_stop'?** 

The 'outermost_start' and 'outermost_stop' are the "outer bounds" of the particular variant reported to dbVar.  The outermost_start is the lowest coordinate from among the three possible start coordinates in dbVar: outer start, start, and inner start.  Similarly, outermost stop is the highest coordinate from the three possible stop coordinates in dbVar: inner stop, stop, and outer stop.

These dbVar placement coordinates are described as follows:

- **start-stop coordinates**: used to define events where breakpoints are known to basepair resolution. 

- **inner start-stop coordinates**: used to define regions that are known to be affected by a variant, but do not define the actual breakpoints. The breakpoints lie outside of the defined region. 

- **outer start-stop coordinates**: used to define the absolute outer boundary of a variation event but do not define the actual breakpoints. The breakpoints lie inside of the defined region.

Please see the dbVar data model for greater detail at: [https://www.ncbi.nlm.nih.gov/dbvar/content/overview/#datamodel](url)

> **Are there other coordinates we are not seeing in the data file? How do we know what they represent?**

Yes, since the NR files only contain the outer bounds of the variant, there is at present no indication as to whether, e.g. the outermost_start is an outer start, a start, or an inner start.  Nor is there any specific indication as to whether or not additional coordinates, within the outer bounds, for a given variant were included in a submission.  

> **2. What is 'SV_count'? How does it relate to "nsv"s and "nssvs"?**

The SV count in this context is the number of ssvs that appear in a particular NR file record.  I'll change the name to ssv_count to more precisely indicate this.

An ssv is a supporting structural variant; instance; or variant call.  Variant calls are the individual instances of structural variation observed in a study and are based on the output of raw data analyses.  Variant calls are prefixed with ‘nssv’ if the data were accessioned at NCBI and ‘essv’ if they were accessioned at EBI.  

Variant regions (SV): Variant regions are regions of the genome that a submitter has defined as containing structural variation. Very little meta-data is contained on these objects, as they are meant to provide a mark on the genome to define regions containing variation. Variant regions point to sets of exemplar variant instances which support the assertion that the region contains variation. Important: Key to understanding dbVar's data model is an awareness that variant regions do not represent reference variants, nor are they idealized representations of individual structural variant events. Rather, they are simply markers on the genome to denote regions within which structural variation has been observed. It may be helpful to think of variant regions as similar to ss-IDs used in dbSNP - they are submitters' assertions concerning the location of variation. Variant region ids are prefixed with ‘nsv’ if the data were accessioned at NCBI and ‘esv’ if t were accessioned at EBI.

"In the broadest sense, SV can be defined as the genomic changes among individuals that are not single nucleotide variants (Tuzun et al. 2005; Eichler et al. 2007). These include insertions, deletions, duplications, inversions, and translocations (Feuk et al. 2006; Sharp et al. 2006) (see Supplemental material (http://genome.cshlp.org/content/19/7/1270/suppl/DC1) for details on types of SV).

"SV among normal individuals is common and ubiquitous."
ref: Genome Res.  2009.   19:  1270-1278.  http://genome.cshlp.org/content/19/7/1270.full

Please see the above link for more detail on SV and ssv.

> **3. How do we look up a publication mentioned in the "study" column? Do you have citations somewhere?**

Yes.  As noted in the README for this GitHub page:

URLs using the study name or variant_accession can be created to access the data in dbVar, e.g.: 

https://www.ncbi.nlm.nih.gov/dbvar/?term=Boone2013

From the right hand side of this URL,  you may click on PubMed in the select box for Find related data
Database to get to the journal article for this dbVar submission.

For the ssv:

https://www.ncbi.nlm.nih.gov/dbvar/?term=nssv1614481

For the SV:

From the latter page you may click on the "Variant Region ID" on the left to see the variant's region in the NCBI Variation Viewer at: 

https://www.ncbi.nlm.nih.gov/dbvar/variants/nsv933473/

I hope this helps.  I'll be glad to try and answer further questions.

Thanks,

John Garner

dbvar-dev@ncbi.nlm.nih.gov

**Comment by JohnG-001** [comment]
@thefferon,

Headers are now applied to all NR files on the FTP sites.

Thanks for your suggestion.

John

dbvar-dev@ncbi.nlm.nih.gov
