### ISSUE TITLE
What are 'outermost_start' and 'outermost_stop'?

### ISSUE THREAD

**Issue by thefferon** [ncbi/dbvar#8]
The column headers in the README list columns 2 and 3 as "outermost_start" and "outermost_stop". What does that mean - are there other, less "outer", starts and/or stops you are not showing?

The only explanation in the README is (in Example record 1):
> The non-redundant coordinates for this record in dbVar are chr1, with an outermost start of 10001 and outermost stop of 1535693.

Does this indicate there is breakpoint ambiguity? How can we tell in any given case, since all variants are described using these "outermost"-type terms?

**Comment by JohnG-001** [comment]
1. What are 'outermost_start' and 'outermost_stop'?

The 'outermost_start' and 'outermost_stop' are the "outer bounds" of the particular variant reported to dbVar. The outermost_start is the lowest coordinate from among the three possible start coordinates in dbVar: outer start, start, and inner start. Similarly, outermost stop is the highest coordinate from the three possible stop coordinates in dbVar: inner stop, stop, and outer stop.

These dbVar placement coordinates are described as follows:

- start-stop: coordinates: used to define events where breakpoints are known to basepair resolution.

- inner start-stop coordinates: used to define regions that are known to be affected by a variant, but do not define the actual breakpoints. The breakpoints lie outside of the defined region.

- outer start-stop coordinates: used to define the absolute outer boundary of a variation event but do not define the actual breakpoints. The breakpoints lie inside of the defined region.

Since the NR files only contain the outer bounds of the variant, there is at present no indication as to whether, e.g. the outermost_start is an outer start, a start, or an inner start. Nor is there any specific indication as to whether or not additional coordinates, within the outer bounds, for a given variant were included in a submission.

Please see the dbVar data model for greater detail at: https://www.ncbi.nlm.nih.gov/dbvar/content/overview/#datamodel

Thanks for your question. 

John
dbvar-dev@ncbi.nlm.nih.gov
